#!/bin/bash

##
# QA
##

lint() {
    git add .; uvx pre-commit run --all-files # uvx run package one time by borrowing installing
}

commit() {
    uvx --from commitizen cz commit
}

##
# Docker
##

dev() {
    uv run uvicorn app.main:app --reload
}

up() {
    docker compose -f "./docker/local/docker-compose.yml" up --build -d
}

down() {
    docker compose -f "./docker/local/docker-compose.yml" down
}

local-up() {
    docker compose -f "local.yml" up --build -d
}

local-down() {
    docker compose -f "local.yml" down
}

##
# DB
##

migrations() {
    if [ -z "$1" ]; then
        echo "Error: migration message is required."
        echo "Usage: ./run migrations 'your message here'"
        exit 1
    fi
    alembic revision --autogenerate -m "$1"
}

migrate() {
    alembic upgrade head
}

db-shell() {
    docker compose -f "local.yml" exec db psql -U schedule_app -d schedule_system
}

"$@"
